
core:
  devMode: false
  measuresSnapshot:
    attempts: 5
    attemptsInterval: 100
    logger:
      rootLogger:
        appenders:
            - default
        level: trace
      appenders:
        default:
          class: LoggerAppenderFile
          layout:
            class: LoggerLayoutSimple
          params:
            file: './logs/measures_snapshot.log'
            append: false

db:
  driver: "pdo_mysql"
  host: "127.0.0.1"
  dbname: "sardegna_stazioninew"
  user: "root"
  password: ""

proxy:
    custom: true
    relativePath: "/proxies"
doctrine:
    entitiesRelativePath: "/src"